org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4

minecraft_version=1.21.1
neo_version=21.1.250

mod_id=terraforge_rpg
mod_group_id=com.terraforge.rpg
mod_name=TerraForge RPG
mod_version=0.1.0-alpha
mod_description=Experience Terraria completely rebuilt in 3D Minecraft Java Edition with deep RPG systems.
mod_authors=Alza, TerraForge Team
